<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    Welcome on board!
    </h3>
  </div>
  <div class="panel-body">
    <p>
    Welcome on my site. That's where I put my stuffs. Just enjoy!
    </p>
    <p>
      <span class="glyphicon glyphicon-warning-sign"></span>
    As you can notice, the work is in progress. Some ajustments have to be done.
    Some content has to be added. It will come as the time passes by.
    </p>
  </div>
</div>
