<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    Welcome on board!
    </h3>
  </div>
  <div class="panel-body">
    <p>
    Welcome on my site. That's where I put my stuffs. Just enjoy!
    </p>
    <p>
    This site is intended to compute informations I don't want to have to
    remember all the time and that I can share.
    This way, I just have to put a pointer to this site in my really tiny
    memory. :-)
    </p>
    <hr/>
    <p>
      <span class="glyphicon glyphicon-warning-sign"></span>
    As you can notice, the work is in progress. Some adjustments are to be done.
    Some content has to be added. It will come as the time passes by.
    </p>
    <p>
    If you find errors, you can either send me a mail to herlantj at gmail
    dot com or do a pull request on github.
    </p>
  </div>
</div>
