<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    In this category you'll find tips about the asciidoc tool which this website
    is generated with.
    </p>
    <p>
    The project repository can be found on
    <a href="http://code.google.com/p/asciidoc">Google code asciidoc repo</a>
    and the documentation on <a href="http://asciidoc.org/">asciidoc.org</a>
    </p>
  </div>
</div>
