<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    In this category you'll find some things I use in my day-to-day DBA life
    and also some stuffs like notes I took for Oracle certifications which I put
    there for anyone which it could be helpfull for.
    </p>
  </div>
</div>
