<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    In this category you'll find tips about the imagevue website generator
    (photo gallery websites). I don't use this tool but a friend of mine do and
    needs sometimes to modify it, so I document thoses modifications here!
    </p>
  </div>
</div>
