<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    On this category you'll find mainly the notes I took while working those
    certifications exams. These notes are not a complete review of the
    certification path, only things I noticed to be more or less interesting.
    </p>
    <p>
    Those are only Oracle Database 11GR2 certifications.
    </p>
    The exams I worked for (or am still working for) are:
    <ul>
      <li>
      Exam 1Z0-047 is to get the "Oracle Database: SQL Certified Expert".
      </li>
      <li>
      Exam 1Z0-052 is to get the OCA certification (1Z0-051 was not needed here because
        superseeded by the fact I passed 1Z0-047)
      </li>
      <li>
      Exam 1Z0-053 is to get the OCP certification.
      </li>
    </ul>
  </div>
</div>
