<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    In this category you'll find things that I found interesting to keep in mind
    about Perl. Those are often things I use in AIX environments to simulate the
    behaviour of some Linux commands I don't have there.
    </p>
  </div>
</div>
