<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    What will you find in this category?
    </h3>
  </div>
  <div class="panel-body">
    <p>
    In this category you'll find Perl one-liners that I found interesting to 
    keep in mind. Those are often things I use in AIX environments to simulate the
    behaviour of some Linux commands I don't have there. I is also usefull when
    working on windows (I use the perl version that ships with Oracle) to
      find a more friendly/usual environement.
    </p>
  </div>
</div>
